import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
export function TopNav(){
  return(
    <nav className="flex w-full h-[70px] bg-green-200 items-center justify-between text-2xl border-b b-[5px] font-semibold">
      <div>Gallery</div>
      <div>SignIn</div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      
      <body className='flex flex-col gap-4'>
      <TopNav/>
        {children}</body>
    </html>
  );
}
